language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
script:
- npm run build
addons:
  ssh_known_hosts:
    - 91.121.88.71
before_deploy:
- openssl aes-256-cbc -K $encrypted_f6439b450e9f_key -iv $encrypted_f6439b450e9f_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build alavaud@91.121.88.71:/usr/share/nginx/html
  on:
    branch: dev
